gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the Island of Bretona\p"
	.string "My name is Decc.\p"
	.string "I'll be your welcome guide here.\p"
	.string "\n"
	.string "$"

gText_Birch_Pokemon::
	.string "Check out this sweet ball\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Our island here is very unique,\n"
	.string "and is home to hundreds of\l"
	.string "species of POKéMON.\p"
	.string "While there are lots of wild\n"
	.string "POKéMON here, there are not so\l"
	.string "many people on Bretona.\p"
	.string "However, the thirst for battles\n"
	.string "is stronger than anywhere else!\p"
	.string "The gym leaders here are no\n"
	.string "slouches. They take their roles\l"
	.string "very seriously, and it shows.\p"
	.string "The only way to succeed here is\n"
	.string "using careful strategy, or\l"
	.string "using complete choas\p"
	.string "\n"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Right then,\n"
	.string "what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's taking\n"
	.string "the Pokemon League Challenge.\n"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll see you soon.\n"
	.string "I'll be waiting at the docks!\p"
	.string "$"
